# Generated by Django 5.1.1 on 2024-09-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_attendance_phonenumber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
        migrations.DeleteModel(
            name="MembershipPlan",
        ),
        migrations.DeleteModel(
            name="Trainer",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="description",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phonenumber",
        ),
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
